### PR TITLE
Bigger eri3

### PR DESCRIPTION
**Pull request by loriab**
- [x] updates to v2.9.0
- [x] uses split-AM for eri3 to allow bigger AM build w/i the 6h time frame. see NOTES file for details.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] ~Bumped the build number (if the version is unchanged)~
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by loriab** [comment]
@conda-forge-admin, please rerender

**Comment by loriab** [comment]
@conda-forge-admin, please rerender

**Comment by loriab** [comment]
@conda-forge-admin, please rerender

**Comment by loriab** [comment]
@conda-forge-admin, please rerender

**Comment by loriab** [comment]
@conda-forge-admin, please rerender

**Comment by loriab** [comment]
@conda-forge-admin, please rerender

**Comment by loriab** [comment]
@conda-forge-admin, please rerender

**Comment by loriab** [comment]
@matt-chan (horton) and @jan-janssen (votca) and @timostrunk (cp2k): sorry folks, I released a new L2 last night with (1) v2.9 update and (2) higher AM ints (see NOTES file in this PR for details), and I completely forgot that different AM isn't hot swapable so you'll probably segfault if not pinned to x.x . Please rebuild or pin.

**Comment by matt-chan** [comment]
Thanks @loriab ! 

Also, not sure if you tried playing around with the conga-forge timeout parameter: https://conda-forge.org/docs/maintainer/conda_forge_yml/#azure

Seems like you can go past 6h if you want?

**Comment by loriab** [comment]
Thanks, @matt-chan, I haven't tried adjusting that up, but I'll keep it in mind. I tested a 7-7-3, and that was right at 6h. But I think 6z is a pretty good compromise. I keep a _really_ big AM build for Linux over at psi4 channel in case that's ever useful.

**Pull request merged**
